services:
  db:
    image: postgres:16-alpine
    container_name: prisma-db
    environment:
      POSTGRES_USER: prismauser
      POSTGRES_PASSWORD: prismapassword
      POSTGRES_DB: prismadb
    ports:
      - "5432:5432"
    volumes:
      - prisma-db-data:/var/lib/postgresql/data

volumes:
  prisma-db-data:
